server:
  port: 8001


eureka:
  client:
    register-with-eureka: true    #false表识不向注册中心注册自己
    fetch-registry: true   #false表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      #这次中心地址
      defaultZone: http://eureka7001.com:7001/eureka/
#  server:
#    enable-self-preservation: false

spring:
  application:
    name: cloud-provider-hystrix-payment
#    eviction-interval-timer-in-ms: 2000